-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN', 'FORM_ADMIN') NOT NULL DEFAULT 'STAFF';

-- AlterTable
ALTER TABLE `ApprovalFlowStep` MODIFY `role` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN', 'FORM_ADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `ApprovalFlowStep` MODIFY `fallbackRole` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN', 'FORM_ADMIN') NULL;

-- CreateTable
CREATE TABLE `FormTypeAdmin` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `formTypeId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `FormTypeAdmin_formTypeId_idx`(`formTypeId`),
    UNIQUE INDEX `FormTypeAdmin_userId_formTypeId_key`(`userId`, `formTypeId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `FormTypeAdmin` ADD CONSTRAINT `FormTypeAdmin_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FormTypeAdmin` ADD CONSTRAINT `FormTypeAdmin_formTypeId_fkey` FOREIGN KEY (`formTypeId`) REFERENCES `FormType`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
