-- AlterTable
ALTER TABLE `approvalflowstep` MODIFY `role` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN') NOT NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `role` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN') NOT NULL DEFAULT 'STAFF';
