// import { Role } from "@prisma/client";
import { Role } from "@/generated/enums";
import { hash } from "bcrypt";
import { prisma } from "../lib/prisma";

const division = [
  { id: 1, name: "BUSINESS DEVELOPMENT & STRATEGY" },
  { id: 2, name: "CEO OFFICE" },
  { id: 3, name: "DHMSB OPERATIONS" },
  { id: 4, name: "ENGINEERING AND RD" },
  { id: 5, name: "FINANCE PROCUREMENT AND IT" },
  { id: 6, name: "HUMAN CAPITAL AND ESG" },
  { id: 7, name: "OPERATION MANAGEMENT" },
  { id: 8, name: "QUALITY MANAGEMENT" },
];

const department = [
  { id: 1, name: "BUSINESS DEVELOPMENT", divisionId: 1 },
  { id: 2, name: "CEO OFFICE", divisionId: 2 },
  { id: 3, name: "COSTING AND COMMERCIAL", divisionId: 1 },
  { id: 4, name: "CULTURE AND TALENT MANAGEMENT", divisionId: 6 },
  { id: 5, name: "ENERGY MGMT AUTHORITY LIASON", divisionId: 4 },
  { id: 6, name: "ENERGY SOLUTION", divisionId: 3 },
  { id: 7, name: "ENGINEERING MANAGEMENT I", divisionId: 4 },
  { id: 8, name: "ENGINEERING MANAGEMENT II", divisionId: 4 },
  {
    id: 9,
    name: "EQUIPMENT MAINT I - SA 1, SA 2, DHMSB, PEGOH",
    divisionId: 4,
  },
  { id: 10, name: "EQUIPMENT MAINT II - BB, RASA, TM1, TM2", divisionId: 4 },
  { id: 11, name: "ESG HEALTH AND SAFETY", divisionId: 6 },
  { id: 12, name: "FACILITY AND ENERGY MANAGEMENT", divisionId: 4 },
  { id: 13, name: "FINANCE", divisionId: 5 },
  { id: 14, name: "HICOM INTELLIGENT MOBILITY", divisionId: 3 },
  { id: 15, name: "INVENTORY MGMT AND PLANNING", divisionId: 7 },
  { id: 16, name: "IT AND DIGITALISATION", divisionId: 5 },
  { id: 17, name: "MANUFACTURING AND SCM -  BB/RASA", divisionId: 7 },
  { id: 18, name: "MANUFACTURING AND SCM - PEGOH", divisionId: 7 },
  { id: 19, name: "MANUFACTURING AND SCM - PEKAN", divisionId: 7 },
  { id: 20, name: "MANUFACTURING AND SCM - SA 2", divisionId: 7 },
  { id: 21, name: "MANUFACTURING AND SCM - SA1", divisionId: 7 },
  { id: 22, name: "MANUFACTURING AND SCM - TM 1", divisionId: 7 },
  { id: 23, name: "MANUFACTURING AND SCM - TM 2", divisionId: 7 },
  { id: 24, name: "MFG & SCM - DHMSB", divisionId: 3 },
  { id: 25, name: "OPERATION I AND IMP", divisionId: 7 },
  { id: 26, name: "OPERATION II", divisionId: 7 },
  { id: 27, name: "OPERATION III", divisionId: 7 },
  { id: 28, name: "OPERATION IV", divisionId: 7 },
  { id: 29, name: "OPERATIONS", divisionId: 3 },
  { id: 30, name: "PROCESS ENGINEERING", divisionId: 4 },
  { id: 31, name: "PROCUREMENT & VENDOR DEV", divisionId: 5 },
  { id: 32, name: "PROGRAM MANAGEMENT", divisionId: 3 },
  { id: 33, name: "PROGRAM MANAGEMENT I", divisionId: 1 },
  { id: 34, name: "PROGRAM MANAGEMENT II", divisionId: 1 },
  { id: 35, name: "PROGRAM MANAGEMENT III", divisionId: 1 },
  { id: 36, name: "QMS & SQ", divisionId: 8 },
  {
    id: 37,
    name: "QUALITY ASSURANCE & CONTROL - BB, RASA, TM 1 AND TM 2",
    divisionId: 8,
  },
  { id: 38, name: "QUALITY ASSURANCE & CONTROL SA 1", divisionId: 8 },
  { id: 39, name: "QUALITY ASSURANCE & CONTROL SA 2", divisionId: 8 },
  { id: 40, name: "QUALITY ASSURANCE & CONTROL-DEV - MLK PKN", divisionId: 8 },
  { id: 41, name: "QUALITY DEVELOPMENT", divisionId: 8 },
  { id: 42, name: "QUALITY MANAGEMENT", divisionId: 8 },
  { id: 43, name: "QUALITY OPERATIONS", divisionId: 8 },
  { id: 44, name: "RESEARCH AND DEVELOPMENT", divisionId: 4 },
  { id: 45, name: "REWARDS AND ADMIN", divisionId: 6 },
  { id: 46, name: "TOOLING DESIGN AND DEVELOPMENT", divisionId: 4 },
];

const section = [
  { id: 1, name: "ACCOUNT PAYABLE", departmentId: 13 },
  { id: 2, name: "ACCOUNT RECEIVABLE", departmentId: 13 },
  { id: 3, name: "ADMINISTRATION", departmentId: 45 },
  { id: 4, name: "AEROSPACE", departmentId: 33 },
  { id: 5, name: "APPLICATION", departmentId: 16 },
  { id: 6, name: "ASSEMBLY", departmentId: 21 },
  { id: 7, name: "ASSEMBLY - PEGOH", departmentId: 18 },
  { id: 8, name: "ASSEMBLY - SA 2", departmentId: 20 },
  { id: 9, name: "ASSEMBLY - TGM 1 (FIF)", departmentId: 22 },
  { id: 10, name: "ASSEMBLY - TGM 2", departmentId: 23 },
  { id: 11, name: "COMPENSATION & BENEFIT", departmentId: 45 },
  { id: 12, name: "COST AND EXPENDITURE", departmentId: 15 },
  { id: 13, name: "COSTING", departmentId: 3 },
  { id: 14, name: "COSTING", departmentId: 24 },
  { id: 15, name: "CULTURE SECTION", departmentId: 4 },
  { id: 16, name: "CUSTOMER QUALITY AND LAB - SA 2", departmentId: 39 },
  {
    id: 17,
    name: "CUSTOMER QUALITY AND QUALITY ENGINEERING SA 1",
    departmentId: 38,
  },
  {
    id: 18,
    name: "CUSTOMER QUALITY AND QUALITY ENGINEERING SA 1",
    departmentId: 39,
  },
  { id: 19, name: "CUSTOMER SERVICE - SA 1", departmentId: 39 },
  { id: 20, name: "DESIGN", departmentId: 44 },
  { id: 21, name: "EQUIPMENT MNTC ASSEMBLY- FIF", departmentId: 10 },
  { id: 22, name: "EQUIPMENT MNTC ASSEMBLY- PHN 1", departmentId: 10 },
  { id: 23, name: "EQUIPMENT MNTC ASSEMBLY- PHN 1", departmentId: 9 },
  { id: 24, name: "EQUIPMENT MNTC ASSEMBLY- SA 2", departmentId: 9 },
  { id: 25, name: "EQUIPMENT MNTC STAMPING- SA1", departmentId: 9 },
  { id: 26, name: "FABRICATION", departmentId: 24 },
  { id: 27, name: "FACILITY & PLANT MAINTENANCE", departmentId: 5 },
  { id: 28, name: "FACILITY & PLANT MAINTENANCE", departmentId: 12 },
  { id: 29, name: "GENERAL PURCHASES", departmentId: 31 },
  { id: 30, name: "GREEN TECHNOLOGY AND NON AUTO", departmentId: 44 },
  { id: 31, name: "HMS", departmentId: 36 },
  { id: 32, name: "IMPORTED MATERIAL AND COMPONENT", departmentId: 31 },
  { id: 33, name: "INDUSTRIAL ENGINEERING", departmentId: 30 },
  { id: 34, name: "INVENTORY FIXED ASSET MANAGEMENT", departmentId: 13 },
  { id: 35, name: "INVENTORY MANAGEMENT PLANNING - PEGOH", departmentId: 15 },
  { id: 36, name: "INVENTORY MANAGEMENT SYSTEM - BB", departmentId: 15 },
  { id: 37, name: "INVENTORY MANAGEMENT SYSTEM - PEGOH", departmentId: 15 },
  { id: 38, name: "INVENTORY MANAGEMENT SYSTEM - SA 1", departmentId: 15 },
  { id: 39, name: "INVENTORY MANAGEMENT SYSTEM - SA 2", departmentId: 15 },
  { id: 40, name: "INVENTORY MANAGEMENT SYSTEM - TGM 2", departmentId: 15 },
  { id: 41, name: "LEARNING & DEVELOPMENT", departmentId: 4 },
  { id: 42, name: "LEGAL AND SECRETARIAT", departmentId: 2 },
  { id: 43, name: "LOGISTIC - SA 2", departmentId: 20 },
  { id: 44, name: "MANUFACTURING - BB", departmentId: 17 },
  { id: 45, name: "MANUFACTURING DHMSB", departmentId: 24 },
  { id: 46, name: "MARKETING & SALES", departmentId: 1 },
  { id: 47, name: "MFG. PROCESS PLANNING", departmentId: 46 },
  { id: 48, name: "NEW PROJECT DEVELOPMENT", departmentId: 44 },
  { id: 49, name: "NON AUTO", departmentId: 34 },
  { id: 50, name: "PISE SERIES MODEL", departmentId: 35 },
  { id: 51, name: "PRO. MGMT NON AUTO", departmentId: 14 },
  { id: 52, name: "PRO. MGMT. HONDA", departmentId: 34 },
  { id: 53, name: "PRO. MGMT. OTHERS", departmentId: 33 },
  { id: 54, name: "PRO. MGMT. PERODUA", departmentId: 33 },
  { id: 55, name: "PRO. MGMT. PERODUA", departmentId: 34 },
  { id: 56, name: "PROCESS DEVELOPMENT", departmentId: 30 },
  { id: 57, name: "PROCESS IMPROVEMENT", departmentId: 30 },
  { id: 58, name: "PROCESS IMPROVEMENT", departmentId: 36 },
  { id: 59, name: "PROGRESS CONTROL- SA 2", departmentId: 20 },
  { id: 60, name: "PROJECT", departmentId: 9 },
  { id: 61, name: "PROJECT AND DEVELOPMENT", departmentId: 16 },
  { id: 62, name: "PROJECT MMCMM", departmentId: 19 },
  { id: 63, name: "QD CENTRAL", departmentId: 41 },
  { id: 64, name: "QD CENTRAL", departmentId: 46 },
  { id: 65, name: "QD NORTHERN", departmentId: 41 },
  { id: 66, name: "QD SOUTHERN", departmentId: 40 },
  { id: 67, name: "QUALITY ASSURANCE - BB", departmentId: 37 },
  { id: 68, name: "QUALITY ASSURANCE - PEGOH", departmentId: 40 },
  { id: 69, name: "QUALITY ASSURANCE - TGM 2", departmentId: 37 },
  { id: 70, name: "QUALITY ASSURANCE- FIF", departmentId: 37 },
  { id: 71, name: "QUALITY CONTROL - FIF", departmentId: 37 },
  { id: 72, name: "QUALITY CONTROL - PEGOH", departmentId: 40 },
  { id: 73, name: "QUALITY CONTROL - SA 2", departmentId: 39 },
  { id: 74, name: "QUALITY CONTROL ASSY STPG - SA 1", departmentId: 38 },
  { id: 75, name: "QUALITY MANAGEMENT (PEKAN)", departmentId: 40 },
  { id: 76, name: "QUALITY SYSTEM", departmentId: 36 },
  { id: 77, name: "RAW MATERIALS & COMPONENTS", departmentId: 31 },
  { id: 78, name: "RECEIVING - SA 2", departmentId: 20 },
  { id: 79, name: "RECRUITMENT", departmentId: 4 },
  { id: 80, name: "REPORTING TAXATION", departmentId: 13 },
  { id: 81, name: "SHE", departmentId: 11 },
  { id: 82, name: "STAMPING", departmentId: 21 },
  { id: 83, name: "STAMPING- SA 2", departmentId: 20 },
  { id: 84, name: "SUPPLIER QUALITY", departmentId: 36 },
  { id: 85, name: "SUPPLY CHAIN MANAGEMENT - BB", departmentId: 17 },
  { id: 86, name: "SUPPLY CHAIN MANAGEMENT - PEGOH", departmentId: 18 },
  { id: 87, name: "SUPPLY CHAIN MANAGEMENT - SA 1", departmentId: 21 },
  { id: 88, name: "SUPPLY CHAIN MGMT- TGM 1 (FIF)", departmentId: 22 },
  { id: 89, name: "SUPPLY CHAIN MNAGEMENT - TGM 2", departmentId: 23 },
  { id: 90, name: "SYSTEM ADMINISTRATION", departmentId: 16 },
  { id: 91, name: "TE- DIES MAKING", departmentId: 46 },
  { id: 92, name: "TOOLING DESIGN", departmentId: 46 },
  { id: 93, name: "TOOLING FABRICATION", departmentId: 46 },
  { id: 94, name: "TOOLING MAINTENANCE", departmentId: 46 },
  { id: 95, name: "TREASURY AND CASH MANAGEMENT", departmentId: 13 },
  { id: 96, name: "VENDOR MANAGEMENT & DEVELOPMENT", departmentId: 31 },
  { id: 97, name: "WELDING", departmentId: 20 },
];

const hosUsers = [
  {
    EmpNo: "M0623",
    Name: "MOHD FOUAD BIN RAHMAT",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 46,
    Section_Occ: 47,
    Team: "PHNSA",
    Email: "fouad.rahmat@phn.com.my",
  },
  {
    EmpNo: "M0199",
    Name: "ABD ADZIM BIN AHMAD",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 9,
    Section_Occ: 23,
    Team: "PHNSA",
    Email: "adzim@phn.com.my",
  },
  {
    EmpNo: "M0620",
    Name: "MOHD ZAHARAN BIN HASNAWI",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 20,
    Section_Occ: 83,
    Team: "PHNSA2",
    Email: "zaharan@phn.com.my",
  },
  {
    EmpNo: "M0206",
    Name: "M.SANI BIN ABU SAMAH",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 38,
    Section_Occ: 74,
    Team: "PHNSA",
    Email: "msani@phn.com.my",
  },
  {
    EmpNo: "M0172",
    Name: "MD NORIDIN BIN ABD SAMAD",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 15,
    Section_Occ: 12,
    Team: "PHNSA",
    Email: "noridin@phn.com.my",
  },
  {
    EmpNo: "M0173",
    Name: "MOHD REDZUAN BIN MOHD IDRIS",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 21,
    Section_Occ: 82,
    Team: "PHNSA",
    Email: "redzuan@phn.com.my",
  },
  {
    EmpNo: "M0205",
    Name: "MAHAYUDIN BIN MAT DERUS",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 39,
    Section_Occ: 19,
    Team: "PHNSA2",
    Email: "mahayudin@phn.com.my",
  },
  {
    EmpNo: "M0200",
    Name: "ZULKHAIRI BIN MD NOOR",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 17,
    Section_Occ: 85,
    Team: "PHNRASA",
    Email: "zulkhairi@phn.com.my",
  },
  {
    EmpNo: "M0269",
    Name: "SYED ASHARI BIN SYED ALAM",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 20,
    Section_Occ: 59,
    Team: "PHNSA2",
    Email: "syed@phn.com.my",
  },
  {
    EmpNo: "M0262",
    Name: "MOHD RADZI BIN ATAN",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 41,
    Section_Occ: 63,
    Team: "PHNSA2",
    Email: "radzi@phn.com.my",
  },
  {
    EmpNo: "M0647",
    Name: "WAN BAYAN MARAYU BIN WAN SEWALIM BUNGSU",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 23,
    Section_Occ: 10,
    Team: "PHNTGM",
    Email: "w.bayan@phn.com.my",
  },
  {
    EmpNo: "M0270",
    Name: "JOFFREE BIN IBRAHIM",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 46,
    Section_Occ: 91,
    Team: "PHNSA",
    Email: "joffree@phn.com.my",
  },
  {
    EmpNo: "M0577",
    Name: "IDRIS BIN ISHAK",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 44,
    Section_Occ: 48,
    Team: "PHNSA",
    Email: "idris@phn.com.my",
  },
  {
    EmpNo: "M0293",
    Name: "NOR AZLINNA BINTI MOHAMAD",
    Division: 6,
    Designation: "HEAD OF SECTION",
    Department: 45,
    Section_Occ: 3,
    Team: "PHNSA",
    Email: "azlinna@phn.com.my",
  },
  {
    EmpNo: "M0297",
    Name: "ALANG REZA BIN ZAKARIA",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 31,
    Section_Occ: 29,
    Team: "PHNSA",
    Email: "alang.zakaria@hicom-engineering.com",
  },
  {
    EmpNo: "M0294",
    Name: "NORSHAHRANI BIN SAMAT",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 16,
    Section_Occ: 90,
    Team: "PHNSA",
    Email: "shahrani@phn.com.my",
  },
  {
    EmpNo: "M0286",
    Name: "MIRZA RIADIANIE BINTI MUHAMAD NOR",
    Division: 6,
    Designation: "HEAD OF SECTION",
    Department: 4,
    Section_Occ: 15,
    Team: "PHNSA",
    Email: "mirza@phn.com.my",
  },
  {
    EmpNo: "M0247",
    Name: "HASFALILLAH BINTI ABU HASSAN",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 15,
    Section_Occ: 37,
    Team: "PHNPGH",
    Email: "hasfalillah@phn.com.my",
  },
  {
    EmpNo: "M0185",
    Name: "SITI MUNIRAH BINTI MOHAMED ZAIN",
    Division: 1,
    Designation: "HEAD OF SECTION",
    Department: 3,
    Section_Occ: 13,
    Team: "PHNSA2",
    Email: "munirah@phn.com.my",
  },
  {
    EmpNo: "M0296",
    Name: "MOHD AZIZI BIN KUDORI",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 21,
    Section_Occ: 87,
    Team: "PHNSA",
    Email: "azizi@phn.com.my",
  },
  {
    EmpNo: "M0240",
    Name: "EIDURA NORHANNA BINTI ZAKARIA",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 31,
    Section_Occ: 77,
    Team: "PHNSA",
    Email: "eidura@phn.com.my",
  },
  {
    EmpNo: "M0278",
    Name: "SHATIRAH BINTI REJAB",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 16,
    Section_Occ: 5,
    Team: "PHNSA",
    Email: "shatirah@phn.com.my",
  },
  {
    EmpNo: "M0276",
    Name: "SITI AISYAH BINTI ABDUL KARIM",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 37,
    Section_Occ: 67,
    Team: "PHNBB",
    Email: "aisyah@phn.com.my",
  },
  {
    EmpNo: "M0358",
    Name: "OMARAFIQ BIN MOKHTAR",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 21,
    Section_Occ: 6,
    Team: "PHNSA",
    Email: "omarafiq@phn.com.my",
  },
  {
    EmpNo: "M0569",
    Name: "MOHD NAZROL BIN IDRIS",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 41,
    Section_Occ: 65,
    Team: "PHNRASA",
    Email: "nazrol@phn.com.my",
  },
  {
    EmpNo: "M0284",
    Name: "RUZILAWATI BINTI OMAR",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 36,
    Section_Occ: 84,
    Team: "PHNSA2",
    Email: "ruzilawati@phn.com.my",
  },
  {
    EmpNo: "M0494",
    Name: "MOHAMAD QHOSSIM ADAM BIN MD KALIL",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 46,
    Section_Occ: 47,
    Team: "PHNSA",
    Email: "qhossim@phn.com.my",
  },
  {
    EmpNo: "M0476",
    Name: "MOHD HAZAZI BIN MOHD ZAIN",
    Division: 1,
    Designation: "HEAD OF SECTION",
    Department: 33,
    Section_Occ: 53,
    Team: "PHNSA2",
    Email: "hazazi@phn.com.my",
  },
  {
    EmpNo: "M0340",
    Name: "MUHAMMAD RIFA'T BIN HASSAN",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 36,
    Section_Occ: 58,
    Team: "PHNSA2",
    Email: "mrifat@phn.com.my",
  },
  {
    EmpNo: "M0361",
    Name: "MOHAMAD HISYAMUDIN B ZAINAL ABIDIN",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 15,
    Section_Occ: 38,
    Team: "PHNSA",
    Email: "mhisyam@phn.com.my",
  },
  {
    EmpNo: "M0347",
    Name: "NIK MUHD AIZAM BIN MOHD NOOR",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 18,
    Section_Occ: 86,
    Team: "PHNPGH",
    Email: "aizam@phn.com.my",
  },
  {
    EmpNo: "M0310",
    Name: "MUHAMAD FAHMI BIN OTHMAN",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 31,
    Section_Occ: 96,
    Team: "PHNSA",
    Email: "mfahmi@phn.com.my",
  },
  {
    EmpNo: "M0357",
    Name: "MUHAMMAD NAJMI BIN SAYUTI",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 17,
    Section_Occ: 44,
    Team: "PHNBB",
    Email: "najmi@phn.com.my",
  },
  {
    EmpNo: "M0332",
    Name: "MUHAMAD HAZRUL HAKIMIN BIN ABU SHAARI",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 22,
    Section_Occ: 88,
    Team: "PHNFIF",
    Email: "hakimin@phn.com.my",
  },
  {
    EmpNo: "M0593",
    Name: "AMIR HUZAIMIE BIN JAWAHIR",
    Division: 1,
    Designation: "HEAD OF SECTION",
    Department: 34,
    Section_Occ: 52,
    Team: "PHNPGH",
    Email: "amirhuzaimie@phn.com.my",
  },
  {
    EmpNo: "M0352",
    Name: "HALIMAHHUSNA BINTI USOK@ YUSOFF",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 15,
    Section_Occ: 36,
    Team: "PHNBB",
    Email: "husna@phn.com.my",
  },
  {
    EmpNo: "M0501",
    Name: "SITI NURSYAFIQA BINTI ZAINUL ABIDIN",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 39,
    Section_Occ: 16,
    Team: "PHNSA2",
    Email: "nursyafiqa@phn.com.my",
  },
  {
    EmpNo: "M0436",
    Name: "AMIR BIN HARIDAN",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 18,
    Section_Occ: 7,
    Team: "PHNPGH",
    Email: "amir.h@phn.com.my",
  },
  {
    EmpNo: "CS0031",
    Name: "YANTI TJEN",
    Division: 1,
    Designation: "HEAD OF SECTION",
    Department: 1,
    Section_Occ: 46,
    Team: "PHNSA2",
    Email: "yanti@phn.com.my",
  },
  {
    EmpNo: "M0140",
    Name: "SAZALI BIN DERANI",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 17,
    Section_Occ: 85,
    Team: "PHNBB",
    Email: "dsazali@phn.com.my",
  },
  {
    EmpNo: "M0320",
    Name: "NORIZAN BIN OSMAN",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 44,
    Section_Occ: 30,
    Team: "PHNSA1",
    Email: "norizan@phn.com.my",
  },
  {
    EmpNo: "M0464",
    Name: "NOREHAN BINTI MOHAMAD AMIN",
    Division: 5,
    Designation: "HEAD OF SECTION",
    Department: 31,
    Section_Occ: 29,
    Team: "PHNSA1",
    Email: "norehan@phn.com.my",
  },
  {
    EmpNo: "M0219",
    Name: "MUHAMAD ZULKAPLI BIN SELAMAT",
    Division: 1,
    Designation: "HEAD OF SECTION",
    Department: 3,
    Team: "PHNSA2",
    Email: "zulkapli@phn.com.my",
  },
  {
    EmpNo: "M0354",
    Name: "MOHAMAD JUHARI BIN IDRIS",
    Division: 7,
    Designation: "HEAD OF SECTION",
    Department: 21,
    Section_Occ: 82,
    Team: "PHNSA1",
    Email: "juhari@phn.com.my",
  },
  {
    EmpNo: "M0228",
    Name: "JUNAINAH BINTI MOHIDIN",
    Division: 2,
    Designation: "HEAD OF SECTION",
    Department: 2,
    Team: "PHNSA1",
    Email: "junainah@phn.com.my",
  },
  {
    EmpNo: "M0335",
    Name: "MADIHAH BINTI ABDUL MUTALIB",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 37,
    Section_Occ: "QUALITY ASSURANCE - TGM 2",
    Team: "PHNTGM",
    Email: "madihah@phn.com.my",
  },
  {
    EmpNo: "M0288",
    Name: "NAZRUL FAMY BIN FAZIL",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 30,
    Section_Occ: 33,
    Team: "PHNSA1",
    Email: "nazrul@phn.com.my",
  },
  {
    EmpNo: "M0318",
    Name: "TUAN AFFINDI BIN TUAN ABDULLAH",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 9,
    Section_Occ: 25,
    Team: "PHNSA1",
    Email: "affindi@phn.com.my",
  },
  {
    EmpNo: "M0541",
    Name: "RUZYLAILY MAULAD OTHMAN",
    Division: 6,
    Designation: "HEAD OF SECTION",
    Department: 4,
    Section_Occ: 79,
    Team: "PHNSA1",
    Email: "ruzylaily@phn.com.my",
  },
  {
    EmpNo: "M0475",
    Name: "YAZID BIN GHAZALI",
    Division: 1,
  Designation: "HEAD OF SECTION",
    Department: 1,
    Section_Occ: 46,
    Team: "PHNSA2",
    Email: "yazid@phn.com.my",
  },
  {
    EmpNo: "M0327",
    Name: "HAMZAH BIN MOHAMAD",
    Division: 8,
   Designation: "HEAD OF SECTION",
    Department: 36,
    Section_Occ: 76,
    Team: "PHNSA2",
    Email: "mhamzah@phn.com.my",
  },
  {
    EmpNo: "M0317",
    Name: "MUHAMMAD AMIN BIN ZAINAL ABIDIN",
    Division: 4,
     Designation: "HEAD OF SECTION",
    Department: 30,
    Section_Occ: 56,
    Team: "PHNSA1",
    Email: "amin@phn.com.my",
  },
  {
    EmpNo: "M0273",
    Name: "ELFY SALWA BINTI ABDULL YAMIN",
    Division: 4,
    Designation: "HEAD OF SECTION",
    Department: 46,
    Section_Occ: 92,
    Team: "PHNSA1",
    Email: "elfy@phn.com.my",
  },
  {
    EmpNo: "M0563",
    Name: "AHMAD TAJUDDIN BIN KHALID",
    Division: 8,
    Designation: "HEAD OF SECTION",
    Department: 37,
    Section_Occ: 70,
    Team: "PHNFIF",
    Email: "tajuddin@phn.com.my",
  },
];

const hodUsers = [
  {
    EmpNo: "M0035",
    Name: "SABARUDDIN BIN ABU",
    Division: 4,
    Designation: "MANAGER I",
    Department: 5,
    Team: "PHNSA",
    Email: "sabaruddin@phn.com.my",
  },
  {
    EmpNo: "M0628",
    Name: "SHAMSUL KAMAR BIN SULAIMAN",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 21,
    Team: "PHNSA",
    Email: "shamsul.k@phn.com.my",
  },
  {
    EmpNo: "M0469",
    Name: "BASRI BIN YAHYA",
    Division: 6,
    Designation: "HEAD OF DEPARTMENT",
    Department: 45,
    Team: "PHNSA",
    Email: "basri@phn.com.my",
  },
  {
    EmpNo: "M0639",
    Name: "SHAMSHUL ANUAR BIN ABDULLAH",
    Division: 4,
    Designation: "MANAGER II",
    Department: 12,
    Team: "PHNSA",
    Email: "shamshul.anuar@phn.com.my",
  },
  {
    EmpNo: "M0399",
    Name: "AMIRULHAKIM BIN MALIK",
    Division: 8,
    Designation: "SENIOR MANAGER I",
    Department: 43,
    Team: "PHNSA2",
    Email: "a.hakim@phn.com.my",
  },
  {
    EmpNo: "M0204",
    Name: "VASUDEVAN A/L SUBRAMANIAM",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 20,
    Team: "PHNSA2",
    Email: "vasudevan@phn.com.my",
  },
  {
    EmpNo: "M0107",
    Name: "ZAILANUDIN BIN MAT NOH",
    Division: 1,
    Designation: "SENIOR MANAGER I",
    Department: 1,
    Team: "PHNSA2",
    Email: "zailan@phn.com.my",
  },
  {
    EmpNo: "M0203",
    Name: "MOHAMED SHAHZAL BIN ABDUL MAJID",
    Division: 7,
    Designation: "MANAGER II",
    Department: 28,
    Team: "PHNTGM",
    Email: "shahzal@phn.com.my",
  },
  {
    EmpNo: "M0141",
    Name: "AN SHAFFRI BIN A AZIZ",
    Division: 4,
    Designation: "HEAD OF DEPARTMENT",
    Department: 46,
    Team: "PHNSA",
    Email: "anshaffri@phn.com.my",
  },
  {
    EmpNo: "M0760",
    Name: "KAMARUL EFFENDY BIN KHALID",
    Division: 4,
    Designation: "SENIOR MANAGER II",
    Department: 8,
    Team: "PHNSA",
    Email: "effendy@phn.com.my",
  },
  {
    EmpNo: "M0768",
    Name: "FAMY BIN IDRIS",
    Division: 8,
    Designation: "HEAD OF DEPARTMENT",
    Department: 36,
    Team: "PHNSA2",
    Email: "famy.idris@phn.com.my",
  },
  {
    EmpNo: "M0500",
    Name: "WAN RAIZAL BIN WAN AHMAD KUSHAARI",
    Division: 4,
    Designation: "HEAD OF DEPARTMENT",
    Department: 10,
    Team: "PHNTGM",
    Email: "w.raizal@phn.com.my",
  },
  {
    EmpNo: "M0648",
    Name: "SAHROL BAHAR BIN AHMAD",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 23,
    Team: "PHNTGM",
    Email: "sahrol@phn.com.my",
  },
  {
    EmpNo: "M0168",
    Name: "NASAH BINTI DAWAM",
    Division: 6,
    Designation: "MANAGER II",
    Department: 4,
    Team: "PHNSA",
    Email: "nasah@phn.com.my",
  },
  {
    EmpNo: "M0331",
    Name: "MUSTAFAR KAMAL BIN BAHANURDIN",
    Division: 1,
    Designation: "MANAGER II",
    Department: 3,
    Team: "PHNSA2",
    Email: "mustafar@phn.com.my",
  },
  {
    EmpNo: "M0715",
    Name: "HUSNIYATI BINTI MOHD AMIN",
    Division: 5,
    Designation: "HEAD OF DEPARTMENT",
    Department: 13,
    Team: "PHNSA",
    Email: "husniyati@phn.com.my",
  },
  {
    EmpNo: "M0718",
    Name: "MOHAMAD RIZVI BIN OTHMAN",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 15,
    Team: "PHNSA",
    Email: "rizvi@phn.com.my",
  },
  {
    EmpNo: "M0603",
    Name: "JALALUDDIN BIN HAJIS",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 22,
    Team: "PHNFIF",
    Email: "jalal@phn.com.my",
  },
  {
    EmpNo: "M0495",
    Name: "MOHD FAIRUZ BIN ABDUL RANI",
    Division: 1,
    Designation: "HEAD OF DEPARTMENT",
    Department: 33,
    Team: "PHNSA2",
    Email: "fairuz@phn.com.my",
  },
  {
    EmpNo: "M0192",
    Name: "SALFARINA BINTI ROZEMAN",
    Division: 4,
    Designation: "MANAGER II",
    Department: 44,
    Team: "PHNSA",
    Email: "salfarina@phn.com.my",
  },
  {
    EmpNo: "M0387",
    Name: "ZAHID BIN ZAINAL",
    Division: 3,
    Designation: "HEAD OF DEPARTMENT",
    Department: 32,
    Team: "PHNSA2",
    Email: "zahid@phn.com.my",
  },
  {
    EmpNo: "M0308",
    Name: "KAMARUNNISA BIN MISNAN",
    Division: 8,
    Designation: "HEAD OF DEPARTMENT",
    Department: 41,
    Team: "PHNSA2",
    Email: "kamarunnisa@phn.com.my",
  },
  {
    EmpNo: "M0178",
    Name: "MUHAMAD ZUNAIDY BIN ZAINAL ABIDIN",
    Division: 6,
    Designation: "MANAGER II",
    Department: 11,
    Team: "PHNSA2",
    Email: "zunaidy@phn.com.my",
  },
  {
    EmpNo: "M0197",
    Name: "MOHD IZYAN BIN SALLEH",
    Division: 1,
    Designation: "HEAD OF DEPARTMENT",
    Department: 35,
    Team: "PHNFIF",
    Email: "izyan@phn.com.my",
  },
  {
    EmpNo: "M0570",
    Name: "MIOR MOHD FAZAIL BIN ABD HAMID",
    Division: 7,
    Designation: "SENIOR MANAGER I",
    Department: 27,
    Team: "PHNPGH",
    Email: "mior@phn.com.my",
  },
  {
    EmpNo: "M0181",
    Name: "NURULHIDYAH BINTI RAHMAT",
    Division: 5,
    Designation: "SENIOR MANAGER I",
    Department: 31,
    Team: "PHNSA",
    Email: "nhidyah@phn.com.my",
  },
  {
    EmpNo: "M0316",
    Name: "AHMAD JAMLEE BIN MOHD RAZALI",
    Division: 4,
    Designation: "MANAGER II",
    Department: 7,
    Team: "PHNSA",
    Email: "jamlee@phn.com.my",
  },
  {
    EmpNo: "M0638",
    Name: "LOKMAN HAKIM BIN LOT",
    Division: 8,
    Designation: "HEAD OF DEPARTMENT",
    Department: 39,
    Team: "PHNSA2",
    Email: "l.hakim@phn.com.my",
  },
  {
    EmpNo: "M0210",
    Name: "NOOR AZWANA BINTI MOHAMED@MOHAMAD",
    Division: 5,
    Designation: "HEAD OF DEPARTMENT",
    Department: 16,
    Team: "PHNSA",
    Email: "azwana@phn.com.my",
  },
  {
    EmpNo: "M0363",
    Name: "KHAIRUL FADZLIE BIN MOHMOOD @ MAHMOOD",
    Division: 1,
    Designation: "HEAD OF DEPARTMENT",
    Department: 34,
    Team: "PHNSA2",
    Email: "fadzlie@phn.com.my",
  },
  {
    EmpNo: "M0336",
    Name: "OZAL TUAH BIN ABD RAHIM",
    Division: 3,
    Designation: "HEAD OF DEPARTMENT",
    Department: 6,
    Team: "PHNSA2",
    Email: "ozal@phn.com.my",
  },
  {
    EmpNo: "M0644",
    Name: "NURRUL HIZZA BINTI ABDUL HAMID",
    Division: 4,
    Designation: "MANAGER I",
    Department: 9,
    Team: "PHNSA",
    Email: "nurrul.hizza@phn.com.my",
  },
  {
    EmpNo: "M0669",
    Name: "FARIDZUL HAFIFI BIN CHE HASIM",
    Division: 7,
    Designation: "HEAD OF DEPARTMENT",
    Department: 18,
    Team: "PHNPGH",
    Email: "faridzulhafifi@phn.com.my",
  },
  {
    EmpNo: "M0339",
    Name: "MOHAMAD HARITH BIN ABDUL GHANI",
    Division: 4,
    Designation: "HEAD OF DEPARTMENT",
    Department: 30,
    Team: "PHNSA",
    Email: "harith@phn.com.my",
  },
  {
    EmpNo: "M0337",
    Name: "MOHAMAD MAHADI BIN ZAHRIN",
    Division: 8,
    Designation: "HEAD OF DEPARTMENT",
    Department: 38,
    Team: "PHNSA",
    Email: "mahadi@phn.com.my",
  },
];

const hodDiv = [
  {
    EmpNo: "M0734",
    Name: "ADIL AFFANDY BIN OTHMAN",
    Division: 5,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA",
    Email: "adil.othman@phn.com.my",
  },
  {
    EmpNo: "M0069",
    Name: "ALIAS BIN MOHAMED LELA",
    Division: 6,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA",
    Email: "alias@phn.com.my",
  },
  {
    EmpNo: "M0481",
    Name: "TAY CHIN KAH",
    Division: 1,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA2",
    Email: "robin@phn.com.my",
  },
  {
    EmpNo: "M0298",
    Name: "SAIPUL ISLAM BIN ZAINAL ABIDIN",
    Division: 4,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA",
    Email: "zsaipul@phn.com.my",
  },
  {
    EmpNo: "M0759",
    Name: "AZRAQ BIN ASHARI",
    Division: 8,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA2",
    Email: "azraq@phn.com.my",
  },
  {
    EmpNo: "M0348",
    Name: "MOHD SHAZALI BIN ABDUL YUSOH",
    Division: 7,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA1",
    Email: "shazali@phn.com.my",
  },
  {
    EmpNo: "M0763",
    Name: "NAZARI BIN MOHD JEMADI",
    Division: 3,
    Designation: "HEAD OF DIVISION",
    Team: "PHNSA2",
    Email: "nazari@phn.com.my",
  },
];

async function main() {
  const defaultPassword = "P@ss1234";
  const hashedPassword = await hash(defaultPassword, 12);

  const seedDivision = await prisma.division.createMany({
    data: division,
  });

  const seedDepartment = await prisma.department.createMany({
    data: department,
  });

  const seedSection = await prisma.section.createMany({
    data: section,
  });

  const hodDivData = hodDiv.map((user) => ({
    fullname: user.Name,
    staffid: user.EmpNo,
    email: user.Email,
    designation: user.Designation,
    role: Role.HEAD_OF_DIVISION,
    password: hashedPassword,
    divisionId: user.Division,
    workLocation: user.Team,
  }));

  const userHodData = hodUsers.map((user) => ({
    fullname: user.Name,
    staffid: user.EmpNo,
    email: user.Email,
    designation: user.Designation,
    role: Role.HEAD_OF_DEPARTMENT,
    password: hashedPassword,
    departmentId: user.Department,
    divisionId: user.Division,
    workLocation: user.Team,
  }));

  const usersData = hosUsers.map((user) => ({
    fullname: user.Name,
    staffid: user.EmpNo,
    email: user.Email,
    designation: user.Designation,
    role: Role.HEAD_OF_SECTION,
    password: hashedPassword,
    sectionId: typeof user.Section_Occ === 'number' ? user.Section_Occ : parseInt(user.Section_Occ as string, 10),
    departmentId: user.Department,
    divisionId: user.Division,
    workLocation: user.Team,
  }));

  const formattedData = [...hodDivData, ...userHodData, ...usersData];

  const result = await prisma.user.createMany({
    data: formattedData,
  });

  console.log("division count: ", seedDivision.count);
  console.log("department count: ", seedDepartment.count);
  console.log("section count: ", seedSection.count);
  console.log(`Inserted ${result.count} management users.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
