-- AlterTable
ALTER TABLE `ApprovalFlowStep` ADD COLUMN `approvalMode` ENUM('ALL', 'ANY') NOT NULL DEFAULT 'ALL',
    ADD COLUMN `approverSource` ENUM('ROLE', 'MANUAL', 'FORM_FIELD') NOT NULL DEFAULT 'ROLE',
    ADD COLUMN `fallbackRole` ENUM('STAFF', 'HEAD_OF_SECTION', 'HEAD_OF_DEPARTMENT', 'HEAD_OF_DIVISION', 'TOP_MANAGEMENT', 'ADMIN', 'COMPLIANCE_ADMIN') NULL,
    ADD COLUMN `formFieldKey` VARCHAR(191) NULL;
